# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisor', '0002_auto_20170714_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('user', 'event')]),
        ),
    ]
